// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3zLwUxPmhOgX0AE9AthUnwZs_ro6uZvI',
    appId: '1:92147769874:web:3b8f4fe6d22d99d3d46ecb',
    messagingSenderId: '92147769874',
    projectId: 'campuspro-cabab',
    authDomain: 'campuspro-cabab.firebaseapp.com',
    storageBucket: 'campuspro-cabab.appspot.com',
    measurementId: 'G-GLDS2RF70R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeNSSCgqhVuI-ROBajqHSRNJcLqYnSmh8',
    appId: '1:92147769874:android:8b5902f00914d14bd46ecb',
    messagingSenderId: '92147769874',
    projectId: 'campuspro-cabab',
    storageBucket: 'campuspro-cabab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwtGgpCK6zqLq5POOXmRgtsq-cjM3ATaQ',
    appId: '1:92147769874:ios:329978a83ccb7957d46ecb',
    messagingSenderId: '92147769874',
    projectId: 'campuspro-cabab',
    storageBucket: 'campuspro-cabab.appspot.com',
    iosBundleId: 'com.example.campusCatalogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwtGgpCK6zqLq5POOXmRgtsq-cjM3ATaQ',
    appId: '1:92147769874:ios:329978a83ccb7957d46ecb',
    messagingSenderId: '92147769874',
    projectId: 'campuspro-cabab',
    storageBucket: 'campuspro-cabab.appspot.com',
    iosBundleId: 'com.example.campusCatalogue',
  );
}
